In [1]:
#install pytorch
!pip3 install -U -q http://download.pytorch.org/whl/cu92/torch-0.4.1-cp36-cp36m-linux_x86_64.whl


tcmalloc: large alloc 1073750016 bytes == 0x5884c000 @  0x7f496c2d72a4 0x591a07 0x5b5d56 0x502e9a 0x506859 0x502209 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x507641 0x502209 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x507641 0x504c28 0x502540 0x502f3d 0x507641


In [2]:
!pip3 install torchvision

In [0]:
import torch
import numpy as np

In [0]:
def activation(x):
  
  #sigmoid activation function
  
  return 1/(1+torch.exp(-x))

In [0]:
# Generate some data
torch.manual_seed(0)

# Features are 5 random normal variables
features = torch.randn((1, 5))

# True weights for our data, random normal variables again
weights = torch.randn_like(features)

# bias term
bias = torch.randn((1, 1))

In [0]:
# Calculate the output of this network
y = activation(torch.sum(features * weights) + bias)


In [0]:
# another way of calculating using matrix multiplication
y = activation(torch.mm(features, weights.view(5,1)) + bias)

In [0]:
## Multi-layer neural network

In [0]:
# Generate some data
torch.manual_seed(7)

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]
n_hidden = 2
n_output = 1

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)

# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# bias term for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [10]:
# Calculate the output
h = activation(torch.mm(features, W1) + B1)
output = activation(torch.mm(h, W2) + B2)
print(output)

tensor([[0.3171]])


In [0]:
## Numpy to Torch and back

In [12]:
a = np.random.rand(4,3)
a

array([[0.19204113, 0.47999329, 0.54455652],
       [0.45571788, 0.89017013, 0.7030158 ],
       [0.40837427, 0.85286127, 0.42683563],
       [0.51931366, 0.66513019, 0.88149095]])

In [13]:
b = torch.from_numpy(a)
b

tensor([[0.1920, 0.4800, 0.5446],
        [0.4557, 0.8902, 0.7030],
        [0.4084, 0.8529, 0.4268],
        [0.5193, 0.6651, 0.8815]], dtype=torch.float64)

In [14]:
b.numpy()

array([[0.19204113, 0.47999329, 0.54455652],
       [0.45571788, 0.89017013, 0.7030158 ],
       [0.40837427, 0.85286127, 0.42683563],
       [0.51931366, 0.66513019, 0.88149095]])

In [15]:
b.mul_(2)

tensor([[0.3841, 0.9600, 1.0891],
        [0.9114, 1.7803, 1.4060],
        [0.8167, 1.7057, 0.8537],
        [1.0386, 1.3303, 1.7630]], dtype=torch.float64)

In [16]:
a

array([[0.38408227, 0.95998657, 1.08911304],
       [0.91143576, 1.78034027, 1.4060316 ],
       [0.81674854, 1.70572253, 0.85367126],
       [1.03862731, 1.33026037, 1.76298191]])